### ISSUE TITLE
QA Groot side-by-side with proprietary version

### ISSUE THREAD

**Issue by acobster** [sitecrafting/groot#18]
# Setup:

- [x] Spin up an "avocado" site from the old Groot base
- [x] Spin up a "starfruit" site from the new Conifer/Groot/SCWP foundation
- [x] Write down a list of acceptance criteria to test/behaviors that work in the old (avocado) version
- [ ] Make sure these work in the new (starfruit) version

# Acceptance Criteria:

- [ ] Navigation works responsively (should be *partially* fixed with debouncing bugfix) works as expected
- [ ] Decision: Some lando tooling e.g. `lando webpack` or `lando build` to effectively replace `lando grunt`
- [ ] Views are all functionally the same (e.g. sidebars show up where they're supposed to, visual grid system is the same, etc.)
- [ ] Register button shortcode and verify it visually
- [ ] Basic page layout
- [ ] Accordions
- [ ] Blog archives can blog archive - default category & date filters
- [ ] Make sure no errors/notices/warnings etc. appear on the page (we have debug logging for this)

In general, trust your instincts. If something seems like it isn't working or should work differently, just ask. :)

**Comment by rossabplanalp** [comment]
As a Developer I want sidebars to be responsive to breakpoints
As a Developer I want a register button shortcode
As a Developer I want to be able to create flexible accordions
As a Developer I want to be able to archive blog stories
As a Developer I want to have blog stories to have categories
As a Developer I want to have blog stories to have date filters

**Comment by acobster** [comment]
This works well enough. We are not pursuing Groot as a fully fledged open-source product and it will remain mostly internally oriented for now. We are reasonably confident that this stuff works already, and don't need an extra layer of validation right now.
