### ISSUE TITLE
As a Developer I want to be able to create responsive accordions

### ISSUE THREAD

**Issue by acobster** [sitecrafting/groot#30]
Before we can do this we need to decide how we'll go about displaying default content patterns  "out of the box."

Also need to answer the question: **does this include tabs that respond down to accordions, or is that a separate pattern/user story? should that pattern be included in core Groot at all?**

**Update: no tabs, just the basic accordion pattern.**

# Acceptance Criteria

- [ ] Confirm that each accordion row toggles on click/tap

**Comment by rbhensley** [comment]
No, we don't want tabs that respond to accordions integrated by default. At least not at this time. Tabs are a pretty rare design pattern with the sites we build and when we do use them most of the time its in a very specific scenario not just as a flexible pattern (except for metro parks)
